language: node_js
node_js:
- 12.16.1

script: npm test
after_success: npm run coverage

notifications:
  slack:
    secure: EPcmYwSfJ5Jqi+A6fzy7gOuHTRzBHtgouO0BkCTCjV0y1gnEV0DqxUIoYTCS78gTOm6241m5VdmFm6RwaWaS8ROq72IFXjXpm6g922qDIjiOLQjClNSGbNWW4TQhWHjGSozDR08GLDXKhLV6f7ak+UMitdVcP6Uc9rlyIpBdE/hVVXMURIMESHYbzePn5UyIYMAsgpcPKhGNvvyaFkOrHHuU4RHbBeqhRyp/CmMnDPqtbw++i3X5S7aL6F6flVuVy+7KqVb8oAnqw0d5fBQFTK3RZAsrp7jP9J1JLXTluKOt5QMSOgAx/GD4zbBG5YwtNyjZhRLpI0zPRiDDnXT13BGTQk2a2Pp7kO4FHh8Ul8ASDUwtuvXOUdUUUZXajAa82T1odT/JvZjun8syPpwmJudAQujWMrelTGc4nXzmALFyRQiEI+lgPfY9A3Ww9xA2U7sEbF/INZqZmuNPqQwJlzUe+Ag4Qhkj7PVgQKTzJ3PXUA5/uLQekJ6ePC0cg0YAqyrdpLzOsd7flIWi/3XyqOj8PVg6tiZdu71BSG4Qg9joLAAd4pqitnRsBV1eLPqk49ohm0onIFAa7iRukz6O2benBWiiy2+yjpKhNxMN3vvqjQ/kYeFtWO+nfpOqHZzTCztUfGIvQz4alkIiUHbVpyXJ6RyMrssVs23+8biNQwg=
    on_success: always 
    on_failure: always
    template:
      - 'Repo `%{repository_slug}` *%{result}* build (<%{build_url}|#%{build_number}>) for commit (<%{compare_url}|%{commit}>) on branch `%{branch}`  by %{author}.'
      - 'Execution time: *%{duration}*'
      - 'Message: %{message}'
