name: Node.js CI

on: [push]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm test
      env:
        CI: true
        NODE_ENV: test
        DatabaseUrlT: test.db
        DbClient: sqlite3
        CookieSecret: LOL